In [ ]:
print("Pytorch Day1")

Pytorch Day1


In [ ]:
import torch
import pandas as pd
import numpy as np

In [ ]:
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [ ]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim


0

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
#vector

In [ ]:
vector=torch.tensor([2,2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix=torch.tensor([[1,2],[2,1]])
matrix

tensor([[1, 2],
        [2, 1]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#random tensors
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.2449, 0.6712, 0.2887, 0.5856],
        [0.5610, 0.4328, 0.1753, 0.4733],
        [0.6508, 0.2700, 0.0152, 0.3956]])

In [ ]:
random_tensor_imgsize=torch.rand(size=(3,244,244))
random_tensor_imgsize


tensor([[[0.7163, 0.8011, 0.2299,  ..., 0.9006, 0.1544, 0.3681],
         [0.8953, 0.8221, 0.7546,  ..., 0.5612, 0.1681, 0.7662],
         [0.9519, 0.0815, 0.1687,  ..., 0.3579, 0.5380, 0.3164],
         ...,
         [0.7005, 0.5950, 0.0656,  ..., 0.5231, 0.2526, 0.3801],
         [0.4182, 0.2112, 0.2880,  ..., 0.4613, 0.7261, 0.1608],
         [0.0148, 0.3218, 0.5663,  ..., 0.2322, 0.8482, 0.6027]],

        [[0.4335, 0.0391, 0.9777,  ..., 0.3017, 0.6456, 0.6156],
         [0.4038, 0.9887, 0.4517,  ..., 0.7180, 0.5864, 0.4275],
         [0.0901, 0.1987, 0.9526,  ..., 0.0283, 0.4602, 0.0094],
         ...,
         [0.1580, 0.3096, 0.1690,  ..., 0.2147, 0.9446, 0.3996],
         [0.3754, 0.1046, 0.1915,  ..., 0.3789, 0.4406, 0.7513],
         [0.3121, 0.3498, 0.9768,  ..., 0.6288, 0.8742, 0.0332]],

        [[0.3934, 0.3380, 0.0870,  ..., 0.3761, 0.4155, 0.0320],
         [0.8018, 0.0689, 0.5135,  ..., 0.7483, 0.1560, 0.0246],
         [0.7648, 0.9684, 0.3802,  ..., 0.1354, 0.9336, 0.

In [ ]:
#arange tensors
onetoten=torch.arange(0,11)
onetoten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#zeroslike
onetothirty=torch.zeros_like(input=onetoten)
onetothirty


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#create a tensor
tensoroe=torch.rand(3,4)

In [ ]:
#finout some info about tensor
print(tensoroe)
print(f"Datatype of tensor:{tensoroe.dtype}")
print(f"Device of tensor:{tensoroe.device}")
print(f"Shape of tensor:{tensoroe.shape}")

tensor([[0.4583, 0.1726, 0.8354, 0.1264],
        [0.8972, 0.0302, 0.0065, 0.2124],
        [0.6688, 0.8448, 0.9427, 0.8635]])
Datatype of tensor:torch.float32
Device of tensor:cpu
Shape of tensor:torch.Size([3, 4])


#manipulating tensors
#operation on tensors

In [ ]:
#addition,subtraction,multiplication,division
tensor=torch.tensor([10,3,2])
tensor+10

tensor([20, 13, 12])

In [ ]:
tensor*10

tensor([100,  30,  20])

In [ ]:
tensor

tensor([10,  3,  2])

In [ ]:
tensor-10

tensor([ 0, -7, -8])

There are two ways of matrix torch.multiplication
1.Element wise
2.matrix multiply

In [ ]:
tensor=torch.tensor([1,2,2])
tensor

tensor([1, 2, 2])

In [ ]:
#multiplication by element
print(f"tensor * tensor :{tensor*tensor} ")

tensor * tensor :tensor([1, 4, 4]) 


In [ ]:
#now by matrix multiplication and its just like we do in linear algebra
torch.matmul(tensor,tensor)

tensor(9)

In [ ]:
%%time
torch.matmul(tensor,tensor)


CPU times: user 447 µs, sys: 79 µs, total: 526 µs
Wall time: 443 µs


tensor(9)

There are two main rules for matrix multipllication

1)The inner dimensions must match

(3,2)@(3,2) will not work

(3,2)@(2,3) will work

2)The resulting matrix has the shape of **outer dimensions**

(2,3)@(3,2) will result into (2,2)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.7392, 0.3936, 0.0602],
        [0.2825, 0.1500, 0.0153],
        [0.6183, 0.3314, 0.0953]])

How to change dimensins of matrix for multiplication purpose

In [ ]:
# by taking transpose of the matrix
tensorA=torch.rand(2,3)
tensorB=torch.rand(2,3)
tensorB.T
print(f"After multiplying again:{tensorA@tensorB.T} ")


After multiplying again:tensor([[0.5428, 0.6852],
        [0.6478, 1.6522]]) 


**Finding the min,max,mean and sum**


In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.mean(x.type(torch.float32))  #finding mean

tensor(45.)

#Find the position of elemenets in tensor
WE CAN DO THAT USING ARGMIN,ARGMAX FUNCTIONS

#RESHAPING,STACKING,SQUEEZING AND UNSQUEEZING
RESHAPPING: reshapes an input tensor to a desired shape
VIEW:  view returns an input tensor of certain shape while retaining same memory
squeeze: removes all one dimension from tensor
unsqueeze: add one dimension


In [ ]:
batchsize=10
features=25
x=torch.rand(batchsize,features)
x

tensor([[0.0314, 0.2552, 0.6461, 0.4575, 0.4608, 0.1563, 0.1517, 0.9360, 0.2662,
         0.0253, 0.1972, 0.4545, 0.9516, 0.3269, 0.2530, 0.5508, 0.2749, 0.6453,
         0.4026, 0.5449, 0.9552, 0.8656, 0.0869, 0.6735, 0.2124],
        [0.5783, 0.6740, 0.6437, 0.0712, 0.8922, 0.1227, 0.2531, 0.2036, 0.0057,
         0.0041, 0.4884, 0.8851, 0.4091, 0.7485, 0.7111, 0.1926, 0.7490, 0.5118,
         0.7141, 0.5905, 0.9941, 0.7719, 0.3370, 0.7980, 0.8565],
        [0.0123, 0.6859, 0.0202, 0.3022, 0.1805, 0.4381, 0.2996, 0.6263, 0.6600,
         0.0048, 0.1286, 0.9301, 0.7054, 0.0654, 0.2052, 0.9831, 0.6262, 0.6979,
         0.0086, 0.0803, 0.8260, 0.8615, 0.2842, 0.7499, 0.4605],
        [0.3259, 0.2819, 0.0302, 0.5804, 0.5866, 0.0184, 0.0299, 0.5838, 0.9237,
         0.3745, 0.3851, 0.9442, 0.0922, 0.6390, 0.0044, 0.3884, 0.6741, 0.9320,
         0.4336, 0.3765, 0.1576, 0.4127, 0.4789, 0.3845, 0.1305],
        [0.6188, 0.4296, 0.5547, 0.0330, 0.1624, 0.3569, 0.9185, 0.5738, 0.1105,
       

In [ ]:
print(x[0])
print(x[:,0])

tensor([0.0314, 0.2552, 0.6461, 0.4575, 0.4608, 0.1563, 0.1517, 0.9360, 0.2662,
        0.0253, 0.1972, 0.4545, 0.9516, 0.3269, 0.2530, 0.5508, 0.2749, 0.6453,
        0.4026, 0.5449, 0.9552, 0.8656, 0.0869, 0.6735, 0.2124])
tensor([0.0314, 0.5783, 0.0123, 0.3259, 0.6188, 0.5352, 0.1708, 0.0906, 0.2384,
        0.0704])


In [ ]:
print(x[2,0:10])

tensor([0.0123, 0.6859, 0.0202, 0.3022, 0.1805, 0.4381, 0.2996, 0.6263, 0.6600,
        0.0048])
